version: '3.1'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: container:php
    volumes:
     - ./conf.d:/etc/nginx/conf.d
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ../res:/res
