version: '3.1'
services:
  mysql-slave:
    restart: always
    image: xuxueli/xxl-job-admin:2.1.2
    container_name: xxl-job-admin
    ports:
      - 7777:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: '--spring.datasource.url=jdbc:mysql://106.12.190.107:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=123 --xxl.job.login.username=admin --xxl.job.login.password=123456'
      #JAVA_OPTS: '-Xmx512m' java内存参数设置
    volumes:
      - /var/logs/xxl-joba:/data/applogs
    networks:
      - xxl-job
    logging: #服务的日志记录配置。
      driver: 'json-file'
      options:
        max-size: '200k' #最大存储200k
        max-file: '10' #最大日志文件数

networks:
  xxl-job:
    external: false #没有网络则自动创建
