version: '3.1'
services:
  mongo-copy:
    image: mongo
    restart: always
    ports:
      - 27019:27017
    privileged: true
    #volumes:
    #  - $PWD/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 5ec8dc7ad047815cf7dd7165
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8100:8099
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 5ec8dc7ad047815cf7dd7165
