version: '3.1'
services: 
 applets:
   image: dordoka/tomcat:latest
   ports:
    - 8084:8080
   volumes:
    - ./webapps/applets:/opt/tomcat/webapps/applets
    - ./webapps/applets_keys:/opt/tomcat/webapps/ROOT 
   restart: always
   environment:
      - JAVA_OPTS=-Xms1024m -Xmx2048m -XX:PermSize=256M -XX:MaxPermSize=512M

