version: '3.1'
services:
 ftp:
  image: fauria/vsftpd
  container_name: ftp
  restart: always
  ports:
   - '20:20'
   - '21:21'
   - '21100-21110:21100-21110'
  environment:
   - FTP_USER=admin
   - FTP_PASS=edc3000.
   - PASV_ADDRESS={Your Host}
  volumes:
   - ./log:/var/log/vsftpd
   - ./conf/vsftpd:/etc/vsftpd
   - ftp_home:/home/vsftpd
 nginx:
  image: nginx
  container_name: ftp_nginx
  restart: always
  privileged: true
  ports:
   - '9080:80'
  volumes:
   - ./conf/nginx/conf.d:/etc/nginx/conf.d
   - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ftp_home:/opt
  depends_on:
   - ftp
volumes:
 ftp_home:

