version: '4.1'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./plugins:/opt/rabbitmq/temp/plugins
