version: "3.1"
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - ./sonatype-work:/opt/sonatype/sonatype-work
      - /data/nexus-data/:/nexus-data/
