version: '3.1'
services:
  easydarwin:
    image: justtin/easydarwin
    container_name: easydarwin
    restart: always
    ports:
    - 10008:10008
    - 554:554
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
      LOCAL_AUTHORIZATION_ENABLE: 0 #是否启用向服务器推流或者从服务器播放时验证用户名密码. [注意] 因为服务器端并不保存明文密码，所以推送或者播放时，客户端应该输入密码的md5后的值。
      REMOTE_HTTP_AUTHORIZATION_ENABLE: 0 #是否启用远程身份认证，适用于cluster
      AUTHORIZATION_TYPE: Digest #身份认证类型Basic or Digest