version: '3.1'
services:
  php:
    image: php-ext:7.4-fpm
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: php
    ports:
      - 80:80
    volumes:
      - ./res:/res
